"""
Auto-generates a MODEL_CARD.md inside the bundle folder.
Captures dataset info, model architecture, eval metrics, and usage instructions.
"""
from __future__ import annotations
from pathlib import Path
import json
import time


def generate_model_card(
    bundle_path: str,
    modality: str,
    model_name: str,
    training_mode: str,
    task: str,
    classes: list[str],
    hyperparams: dict,
    history: list[dict],
    eval_summary: str = "",
) -> str:
    bundle = Path(bundle_path)
    final  = history[-1] if history else {}

    lines = [
        f"# Model Card — {model_name}",
        "",
        f"> Generated by **NoCode-DL** on {time.strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Overview",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Modality | {modality} |",
        f"| Architecture | {model_name} |",
        f"| Training mode | {training_mode} |",
        f"| Task | {task} |",
        f"| Classes | {', '.join(classes)} |",
        f"| Epochs trained | {final.get('epoch', '—')} |",
        f"| Final val loss | {final.get('val_loss', '—')} |",
        f"| Final val acc | {final.get('val_acc', '—')}{'%' if task == 'classification' else ''} |",
        "",
        "## Hyperparameters",
        "",
        "| Parameter | Value |",
        "|---|---|",
    ]
    for k, v in hyperparams.items():
        lines.append(f"| {k} | {v} |")

    if eval_summary:
        lines += ["", "## Evaluation", "", "```", eval_summary, "```"]

    lines += [
        "",
        "## Usage",
        "",
        "```python",
        "import numpy as np",
        "import onnxruntime as ort",
        "import json",
        "",
        'with open("labels.json") as f: labels = json.load(f)',
        'session = ort.InferenceSession("model.onnx")',
        'input_name = session.get_inputs()[0].name',
        "",
        "# Preprocess your input → x (numpy array)",
        "logits = session.run(None, {input_name: x.astype(np.float32)})[0]",
        "pred   = labels[str(int(logits.argmax(axis=1)[0]))]",
        "print('Predicted:', pred)",
        "```",
        "",
        "## Files in this bundle",
        "",
        "| File | Description |",
        "|---|---|",
        "| `model.onnx` | Exported ONNX model |",
        "| `preprocessing.json` | Input preprocessing config |",
        "| `labels.json` | Class index → label name |",
        "| `inference.py` | Ready-to-run inference script |",
        "| `main.py` | FastAPI inference server (if generated) |",
        "| `MODEL_CARD.md` | This file |",
    ]

    card_path = bundle / "MODEL_CARD.md"
    card_path.write_text("\n".join(lines))
    return str(card_path)
